import type { Metadata } from "next";
import Link from "next/link";
import { Notice, PageHeader, Panel, Tag } from "@/components/ui";
import { scopeLabel, WINDOWS } from "@/lib/analytics/common";
import { can } from "@/lib/auth/rbac";
import { siteById } from "@/lib/domain/master";
import { pageContext, type SearchParams } from "@/lib/server/page";
import { REPORT_TYPES } from "./report-types";

export const metadata: Metadata = { title: "Reports" };

export default async function ReportsPage({ searchParams }: { searchParams: SearchParams }) {
  const { user, scope, windowKey, filter } = await pageContext("reports", searchParams);
  const canGenerate = can(user.role, "report.generate");
  const site = filter.site ? siteById.get(filter.site) : undefined;

  const printHref = (type: string) => {
    const qs = new URLSearchParams({ type });
    if (filter.zone) qs.set("zone", filter.zone);
    if (filter.site) qs.set("site", filter.site);
    qs.set("window", windowKey);
    return `/reports/print?${qs.toString()}`;
  };

  return (
    <>
      <PageHeader
        title="Reports"
        description={`Printable reports built from the same governed figures as the dashboards. Current scope: ${scopeLabel(scope)}, ${WINDOWS[windowKey].label.toLowerCase()}. Change the scope bar above to report on a different zone, site or window.`}
      />

      {!canGenerate && (
        <div className="mb-4">
          <Notice title="Published reports are shared by your team">
            Your role has read-only access. Reports are generated by leadership, operations, engineering or finance users and shared with you once published.
          </Notice>
        </div>
      )}

      <div className="grid gap-4 md:grid-cols-2">
        {REPORT_TYPES.map((r) => {
          const needsSite = r.key === "site" && !site;
          return (
            <Panel
              key={r.key}
              title={r.title}
              description={r.summary}
              actions={r.key === "site" && site ? <Tag tone="brand">{site.name}</Tag> : undefined}
            >
              <ul className="list-disc space-y-1 pl-4 text-[13px] text-ink-2">
                {r.contents.map((c) => (
                  <li key={c}>{c}</li>
                ))}
              </ul>
              <div className="mt-4 flex flex-wrap items-center gap-3">
                {needsSite ? (
                  <p className="text-[13px] text-ink-2">Select a site in the scope bar above to generate a site report.</p>
                ) : canGenerate ? (
                  <Link href={printHref(r.key)} className="btn btn-primary" target="_blank" rel="noopener">
                    Open printable report
                  </Link>
                ) : (
                  <span className="text-[13px] text-ink-3">Read-only role: ask your team for the published copy.</span>
                )}
              </div>
            </Panel>
          );
        })}
      </div>

      <p className="mt-4 text-[12.5px] text-ink-3">
        Every generated report records who generated it, when, and for which scope in the audit log. Reports carry the environment and data mode marker so staging or synthetic output is never mistaken for production figures.
      </p>
    </>
  );
}
